# Generated by Django 2.2.27 on 2022-03-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conentList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterNum', models.CharField(max_length=200)),
                ('chapterTitle', models.CharField(max_length=200)),
                ('chapterAuthor', models.CharField(max_length=200)),
                ('create_house', models.CharField(max_length=200)),
                ('edited_data', models.DateTimeField(verbose_name='date edited')),
            ],
        ),
    ]
